theme: minima
markdown: kramdown

title: |-
    Speeding Up Optimization-based Motion Planning 
    through Deep Learning

author: '{johannes.tenhumberg, leon.sievers, berthold.baeuml}@dlr.de'

header_pages:

include:
    - _pages

exclude:
    - .gitignore
    - Gemfile
    - README.md
    
kramdown:
  hard_wrap: true


