theme: minima
markdown: kramdown

title: |-
    Test test2 test3 test4 test5 test6 test7
    Test test2 test3 test4 test5 test6 test7
    Test test2 test3 test4 test5 test6 test7

author: '{johannes.tenhumberg, leon.sievers, berthold.baeuml}@dlr.de'

header_pages:

include:
    - _pages

exclude:
    - .gitignore
    - Gemfile
    - README.md


