theme: minima
markdown: kramdown

title: Self-Contained and Automatic Calibration of a Multi-Fingered Hand
       Self-Contained and Automatic Calibration of a Multi-Fingered Hand

author: '{johannes.tenhumberg, leon.sievers, berthold.baeuml}@dlr.de'

header_pages:

include:
    - _pages

exclude:
    - .gitignore
    - Gemfile
    - README.md
    
kramdown:
  hard_wrap: true


