theme: minima
markdown: kramdown

title: |-
    Self-Contained and Automatic Calibration of a Multi-Fingered Hand
    Using Only Pairwise Contact Measurements

author: '{johannes.tenhumberg, leon.sievers, berthold.baeuml}@dlr.de'
    
exclude: 
    - .gitignore
    - Gemfile
    - README.md
